version: 2
jobs:
  build:
    working_directory: ~/spring-boot-cognito-client
    branches:
      only:
        - master
        - develop
        - /feature-.*/
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - restore_cache:
          key: spring-boot-cognito-client-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-cognito-client-{{ checksum "pom.xml" }}
      - run: mvn clean install